// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyjpa;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<JpaIntegrationTest>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code JpaIntegrationTest} and its
 * dependencies.
 *
 * Being a {@code Provider<JpaIntegrationTest>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<JpaIntegrationTest>} and handling injection
 * of annotated fields.
 */
public final class JpaIntegrationTest$$InjectAdapter extends Binding<JpaIntegrationTest>
    implements Provider<JpaIntegrationTest>, MembersInjector<JpaIntegrationTest> {
  private Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> persistenceFactory;

  public JpaIntegrationTest$$InjectAdapter() {
    super("au.com.cybersearch2.classyjpa.JpaIntegrationTest", "members/au.com.cybersearch2.classyjpa.JpaIntegrationTest", NOT_SINGLETON, JpaIntegrationTest.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    persistenceFactory = (Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>) linker.requestBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", JpaIntegrationTest.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(persistenceFactory);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<JpaIntegrationTest>}.
   */
  @Override
  public JpaIntegrationTest get() {
    JpaIntegrationTest result = new JpaIntegrationTest();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<JpaIntegrationTest>}.
   */
  @Override
  public void injectMembers(JpaIntegrationTest object) {
    object.persistenceFactory = persistenceFactory.get();
  }

}
