// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyinject;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class ObjectGraphManagerTest$TestModule$$ModuleAdapter extends ModuleAdapter<ObjectGraphManagerTest.TestModule> {
  private static final String[] INJECTS = { };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public ObjectGraphManagerTest$TestModule$$ModuleAdapter() {
    super(au.com.cybersearch2.classyinject.ObjectGraphManagerTest.TestModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public ObjectGraphManagerTest.TestModule newModule() {
    return new au.com.cybersearch2.classyinject.ObjectGraphManagerTest.TestModule();
  }
}
