// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classytask;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<UserTaskContext>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code UserTaskContext} and its
 * dependencies.
 *
 * Being a {@code Provider<UserTaskContext>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<UserTaskContext>} and handling injection
 * of annotated fields.
 */
public final class UserTaskContext$$InjectAdapter extends Binding<UserTaskContext>
    implements Provider<UserTaskContext>, MembersInjector<UserTaskContext> {
  private Binding<InternalHandler> internalHandler;

  public UserTaskContext$$InjectAdapter() {
    super("au.com.cybersearch2.classytask.UserTaskContext", "members/au.com.cybersearch2.classytask.UserTaskContext", NOT_SINGLETON, UserTaskContext.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    internalHandler = (Binding<InternalHandler>) linker.requestBinding("au.com.cybersearch2.classytask.InternalHandler", UserTaskContext.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(internalHandler);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<UserTaskContext>}.
   */
  @Override
  public UserTaskContext get() {
    UserTaskContext result = new UserTaskContext();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<UserTaskContext>}.
   */
  @Override
  public void injectMembers(UserTaskContext object) {
    object.internalHandler = internalHandler.get();
  }

}
