// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyapp;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<ApplicationContext>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code ApplicationContext} and its
 * dependencies.
 *
 * Being a {@code Provider<ApplicationContext>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<ApplicationContext>} and handling injection
 * of annotated fields.
 */
public final class ApplicationContext$$InjectAdapter extends Binding<ApplicationContext>
    implements Provider<ApplicationContext>, MembersInjector<ApplicationContext> {
  private Binding<android.content.Context> context;

  public ApplicationContext$$InjectAdapter() {
    super("au.com.cybersearch2.classyapp.ApplicationContext", "members/au.com.cybersearch2.classyapp.ApplicationContext", NOT_SINGLETON, ApplicationContext.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    context = (Binding<android.content.Context>) linker.requestBinding("android.content.Context", ApplicationContext.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(context);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<ApplicationContext>}.
   */
  @Override
  public ApplicationContext get() {
    ApplicationContext result = new ApplicationContext();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<ApplicationContext>}.
   */
  @Override
  public void injectMembers(ApplicationContext object) {
    object.context = context.get();
  }

}
