// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyapp;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<ApplicationLocale>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code ApplicationLocale} and its
 * dependencies.
 *
 * Being a {@code Provider<ApplicationLocale>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<ApplicationLocale>} and handling injection
 * of annotated fields.
 */
public final class ApplicationLocale$$InjectAdapter extends Binding<ApplicationLocale>
    implements Provider<ApplicationLocale>, MembersInjector<ApplicationLocale> {
  private Binding<ResourceEnvironment> resourceEnvironment;

  public ApplicationLocale$$InjectAdapter() {
    super("au.com.cybersearch2.classyapp.ApplicationLocale", "members/au.com.cybersearch2.classyapp.ApplicationLocale", NOT_SINGLETON, ApplicationLocale.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    resourceEnvironment = (Binding<ResourceEnvironment>) linker.requestBinding("au.com.cybersearch2.classyapp.ResourceEnvironment", ApplicationLocale.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(resourceEnvironment);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<ApplicationLocale>}.
   */
  @Override
  public ApplicationLocale get() {
    ApplicationLocale result = new ApplicationLocale();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<ApplicationLocale>}.
   */
  @Override
  public void injectMembers(ApplicationLocale object) {
    object.resourceEnvironment = resourceEnvironment.get();
  }

}
