// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyapp;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class RoboTest$RoboTestModule$$ModuleAdapter extends ModuleAdapter<RoboTest.RoboTestModule> {
  private static final String[] INJECTS = { "members/au.com.cybersearch2.classyapp.RoboTest", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { au.com.cybersearch2.classyapp.TestAndroidModule.class, };

  public RoboTest$RoboTestModule$$ModuleAdapter() {
    super(au.com.cybersearch2.classyapp.RoboTest.RoboTestModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public RoboTest.RoboTestModule newModule() {
    return new au.com.cybersearch2.classyapp.RoboTest.RoboTestModule();
  }
}
