// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyapp;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<RoboTest>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code RoboTest} and its
 * dependencies.
 *
 * Being a {@code Provider<RoboTest>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<RoboTest>} and handling injection
 * of annotated fields.
 */
public final class RoboTest$$InjectAdapter extends Binding<RoboTest>
    implements Provider<RoboTest>, MembersInjector<RoboTest> {
  private Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> persistenceFactory;

  public RoboTest$$InjectAdapter() {
    super("au.com.cybersearch2.classyapp.RoboTest", "members/au.com.cybersearch2.classyapp.RoboTest", NOT_SINGLETON, RoboTest.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    persistenceFactory = (Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>) linker.requestBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", RoboTest.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(persistenceFactory);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<RoboTest>}.
   */
  @Override
  public RoboTest get() {
    RoboTest result = new RoboTest();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<RoboTest>}.
   */
  @Override
  public void injectMembers(RoboTest object) {
    object.persistenceFactory = persistenceFactory.get();
  }

}
