// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classydb;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class DatabaseAdminImplTest$DatabaseAdminImplTestModule$$ModuleAdapter extends ModuleAdapter<DatabaseAdminImplTest.DatabaseAdminImplTestModule> {
  private static final String[] INJECTS = { "members/au.com.cybersearch2.classyjpa.transaction.EntityTransactionImpl", "members/au.com.cybersearch2.classydb.NativeScriptDatabaseWork", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public DatabaseAdminImplTest$DatabaseAdminImplTestModule$$ModuleAdapter() {
    super(au.com.cybersearch2.classydb.DatabaseAdminImplTest.DatabaseAdminImplTestModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, DatabaseAdminImplTest.DatabaseAdminImplTestModule module) {
    bindings.contributeProvidesBinding("au.com.cybersearch2.classyapp.ResourceEnvironment", new ProvideResourceEnvironmentProvidesAdapter(module));
    bindings.contributeProvidesBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", new ProvidePersistenceFactoryProvidesAdapter(module));
  }

  /**
   * A {@code Binding<au.com.cybersearch2.classyapp.ResourceEnvironment>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<au.com.cybersearch2.classyapp.ResourceEnvironment>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvideResourceEnvironmentProvidesAdapter extends ProvidesBinding<au.com.cybersearch2.classyapp.ResourceEnvironment>
      implements Provider<au.com.cybersearch2.classyapp.ResourceEnvironment> {
    private final DatabaseAdminImplTest.DatabaseAdminImplTestModule module;

    public ProvideResourceEnvironmentProvidesAdapter(DatabaseAdminImplTest.DatabaseAdminImplTestModule module) {
      super("au.com.cybersearch2.classyapp.ResourceEnvironment", NOT_SINGLETON, "au.com.cybersearch2.classydb.DatabaseAdminImplTest.DatabaseAdminImplTestModule", "provideResourceEnvironment");
      this.module = module;
      setLibrary(false);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<au.com.cybersearch2.classyapp.ResourceEnvironment>}.
     */
    @Override
    public au.com.cybersearch2.classyapp.ResourceEnvironment get() {
      return module.provideResourceEnvironment();
    }
  }

  /**
   * A {@code Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvidePersistenceFactoryProvidesAdapter extends ProvidesBinding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>
      implements Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> {
    private final DatabaseAdminImplTest.DatabaseAdminImplTestModule module;

    public ProvidePersistenceFactoryProvidesAdapter(DatabaseAdminImplTest.DatabaseAdminImplTestModule module) {
      super("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", IS_SINGLETON, "au.com.cybersearch2.classydb.DatabaseAdminImplTest.DatabaseAdminImplTestModule", "providePersistenceFactory");
      this.module = module;
      setLibrary(false);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>}.
     */
    @Override
    public au.com.cybersearch2.classyjpa.persist.PersistenceFactory get() {
      return module.providePersistenceFactory();
    }
  }
}
