// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyapp;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<TestClassyApplication>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code TestClassyApplication} and its
 * dependencies.
 *
 * Being a {@code Provider<TestClassyApplication>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<TestClassyApplication>} and handling injection
 * of annotated fields.
 */
public final class TestClassyApplication$$InjectAdapter extends Binding<TestClassyApplication>
    implements Provider<TestClassyApplication>, MembersInjector<TestClassyApplication> {
  private Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> persistenceFactory;

  public TestClassyApplication$$InjectAdapter() {
    super("au.com.cybersearch2.classyapp.TestClassyApplication", "members/au.com.cybersearch2.classyapp.TestClassyApplication", NOT_SINGLETON, TestClassyApplication.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    persistenceFactory = (Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>) linker.requestBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", TestClassyApplication.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(persistenceFactory);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<TestClassyApplication>}.
   */
  @Override
  public TestClassyApplication get() {
    TestClassyApplication result = new TestClassyApplication();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<TestClassyApplication>}.
   */
  @Override
  public void injectMembers(TestClassyApplication object) {
    object.persistenceFactory = persistenceFactory.get();
  }

}
