// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyapp;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class TestClassyApplication$PersistenceModule$$ModuleAdapter extends ModuleAdapter<TestClassyApplication.PersistenceModule> {
  private static final String[] INJECTS = { "members/au.com.cybersearch2.classyapp.TestClassyApplication", "members/au.com.cybersearch2.classyjpa.JpaIntegrationTest", "members/au.com.cybersearch2.classyjpa.entity.PersistenceContainer", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public TestClassyApplication$PersistenceModule$$ModuleAdapter() {
    super(au.com.cybersearch2.classyapp.TestClassyApplication.PersistenceModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public TestClassyApplication.PersistenceModule newModule() {
    return new au.com.cybersearch2.classyapp.TestClassyApplication.PersistenceModule();
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, TestClassyApplication.PersistenceModule module) {
    bindings.contributeProvidesBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", new ProvidePersistenceModuleProvidesAdapter(module));
  }

  /**
   * A {@code Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvidePersistenceModuleProvidesAdapter extends ProvidesBinding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>
      implements Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> {
    private final TestClassyApplication.PersistenceModule module;

    public ProvidePersistenceModuleProvidesAdapter(TestClassyApplication.PersistenceModule module) {
      super("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", IS_SINGLETON, "au.com.cybersearch2.classyapp.TestClassyApplication.PersistenceModule", "providePersistenceModule");
      this.module = module;
      setLibrary(false);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>}.
     */
    @Override
    public au.com.cybersearch2.classyjpa.persist.PersistenceFactory get() {
      return module.providePersistenceModule();
    }
  }
}
