// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyjpa.persist;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;

/**
 * A {@code Binding<PersistenceFactory>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code PersistenceFactory} and its
 * dependencies.
 *
 * Being a {@code Provider<PersistenceFactory>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<PersistenceFactory>} and handling injection
 * of annotated fields.
 */
public final class PersistenceFactory$$InjectAdapter extends Binding<PersistenceFactory>
    implements MembersInjector<PersistenceFactory> {
  private Binding<au.com.cybersearch2.classyapp.ResourceEnvironment> resourceEnvironment;

  public PersistenceFactory$$InjectAdapter() {
    super(null, "members/au.com.cybersearch2.classyjpa.persist.PersistenceFactory", NOT_SINGLETON, PersistenceFactory.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    resourceEnvironment = (Binding<au.com.cybersearch2.classyapp.ResourceEnvironment>) linker.requestBinding("au.com.cybersearch2.classyapp.ResourceEnvironment", PersistenceFactory.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(resourceEnvironment);
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<PersistenceFactory>}.
   */
  @Override
  public void injectMembers(PersistenceFactory object) {
    object.resourceEnvironment = resourceEnvironment.get();
  }

}
