package au.com.cybersearch2.example;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@Entity(name="Simple")
public class SimpleData 
{
	/** This id is generated by the database and set on the object when it is passed to the create method */
    @Id @GeneratedValue
	int id;

	@Column
	private
	long millis;
	
	@Column
	boolean even;

	SimpleData() 
	{
		// needed by ormlite
	}

	public SimpleData(long millis) 
	{
		this.setMillis(millis);
		this.even = ((this.getMillis() % 2) == 0);
	}

	public long getMillis() {
		return millis;
	}

	public void setMillis(long millis) {
		this.millis = millis;
	}

	@Override
	public String toString() 
	{
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("millis=").append(getMillis());
		sb.append(", ").append("even=").append(even);
		return sb.toString();
	}
}
