// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classydb;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class AndroidDatabaseSupportTest$AndroidDatabaseSupportTestModule$$ModuleAdapter extends ModuleAdapter<AndroidDatabaseSupportTest.AndroidDatabaseSupportTestModule> {
  private static final String[] INJECTS = { "members/au.com.cybersearch2.classyapp.ApplicationContext", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public AndroidDatabaseSupportTest$AndroidDatabaseSupportTestModule$$ModuleAdapter() {
    super(au.com.cybersearch2.classydb.AndroidDatabaseSupportTest.AndroidDatabaseSupportTestModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, AndroidDatabaseSupportTest.AndroidDatabaseSupportTestModule module) {
    bindings.contributeProvidesBinding("android.content.Context", new ProvideContextProvidesAdapter(module));
  }

  /**
   * A {@code Binding<android.content.Context>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<android.content.Context>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvideContextProvidesAdapter extends ProvidesBinding<android.content.Context>
      implements Provider<android.content.Context> {
    private final AndroidDatabaseSupportTest.AndroidDatabaseSupportTestModule module;

    public ProvideContextProvidesAdapter(AndroidDatabaseSupportTest.AndroidDatabaseSupportTestModule module) {
      super("android.content.Context", IS_SINGLETON, "au.com.cybersearch2.classydb.AndroidDatabaseSupportTest.AndroidDatabaseSupportTestModule", "provideContext");
      this.module = module;
      setLibrary(false);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<android.content.Context>}.
     */
    @Override
    public android.content.Context get() {
      return module.provideContext();
    }
  }
}
