// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classydb;

import dagger.internal.BindingsGroup;
import dagger.internal.ModuleAdapter;
import dagger.internal.ProvidesBinding;
import javax.inject.Provider;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class AndroidConnectionSourceFactoryTest$AndroidConnectionSourceFactoryTestModule$$ModuleAdapter extends ModuleAdapter<AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule> {
  private static final String[] INJECTS = { "members/au.com.cybersearch2.classydb.ClassyOpenHelperCallbacks", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public AndroidConnectionSourceFactoryTest$AndroidConnectionSourceFactoryTestModule$$ModuleAdapter() {
    super(au.com.cybersearch2.classydb.AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule newModule() {
    return new au.com.cybersearch2.classydb.AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule();
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getBindings(BindingsGroup bindings, AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule module) {
    bindings.contributeProvidesBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", new ProvidePersistenceFactoryProvidesAdapter(module));
  }

  /**
   * A {@code Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>} implementation which satisfies
   * Dagger's infrastructure requirements including:
   *
   * Being a {@code Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>} and handling creation and
   * preparation of object instances.
   */
  public static final class ProvidePersistenceFactoryProvidesAdapter extends ProvidesBinding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>
      implements Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> {
    private final AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule module;

    public ProvidePersistenceFactoryProvidesAdapter(AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule module) {
      super("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", NOT_SINGLETON, "au.com.cybersearch2.classydb.AndroidConnectionSourceFactoryTest.AndroidConnectionSourceFactoryTestModule", "providePersistenceFactory");
      this.module = module;
      setLibrary(false);
    }

    /**
     * Returns the fully provisioned instance satisfying the contract for
     * {@code Provider<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>}.
     */
    @Override
    public au.com.cybersearch2.classyjpa.persist.PersistenceFactory get() {
      return module.providePersistenceFactory();
    }
  }
}
