// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyjpa;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class AndroidJpaIntegrationTest$AndroidJpaIntegrationTestModule$$ModuleAdapter extends ModuleAdapter<AndroidJpaIntegrationTest.AndroidJpaIntegrationTestModule> {
  private static final String[] INJECTS = { "members/au.com.cybersearch2.classyjpa.AndroidJpaIntegrationTest", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { au.com.cybersearch2.classyapp.TestAndroidModule.class, };

  public AndroidJpaIntegrationTest$AndroidJpaIntegrationTestModule$$ModuleAdapter() {
    super(au.com.cybersearch2.classyjpa.AndroidJpaIntegrationTest.AndroidJpaIntegrationTestModule.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public AndroidJpaIntegrationTest.AndroidJpaIntegrationTestModule newModule() {
    return new au.com.cybersearch2.classyjpa.AndroidJpaIntegrationTest.AndroidJpaIntegrationTestModule();
  }
}
