// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyjpa;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binding<AndroidPersistenceFactory>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code AndroidPersistenceFactory} and its
 * dependencies.
 *
 * Being a {@code Provider<AndroidPersistenceFactory>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<AndroidPersistenceFactory>} and handling injection
 * of annotated fields.
 */
public final class AndroidPersistenceFactory$$InjectAdapter extends Binding<AndroidPersistenceFactory>
    implements Provider<AndroidPersistenceFactory>, MembersInjector<AndroidPersistenceFactory> {
  private Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> persistenceFactory;

  public AndroidPersistenceFactory$$InjectAdapter() {
    super("au.com.cybersearch2.classyjpa.AndroidPersistenceFactory", "members/au.com.cybersearch2.classyjpa.AndroidPersistenceFactory", NOT_SINGLETON, AndroidPersistenceFactory.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    persistenceFactory = (Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>) linker.requestBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", AndroidPersistenceFactory.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(persistenceFactory);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<AndroidPersistenceFactory>}.
   */
  @Override
  public AndroidPersistenceFactory get() {
    AndroidPersistenceFactory result = new AndroidPersistenceFactory();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<AndroidPersistenceFactory>}.
   */
  @Override
  public void injectMembers(AndroidPersistenceFactory object) {
    object.persistenceFactory = persistenceFactory.get();
  }

}
