// Code generated by dagger-compiler.  Do not edit.
package au.com.cybersearch2.classyjpa.transaction;

import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;

/**
 * A {@code Binding<EntityTransactionImpl>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 *
 * Owning the dependency links between {@code EntityTransactionImpl} and its
 * dependencies.
 *
 * Being a {@code Provider<EntityTransactionImpl>} and handling creation and
 * preparation of object instances.
 *
 * Being a {@code MembersInjector<EntityTransactionImpl>} and handling injection
 * of annotated fields.
 */
public final class EntityTransactionImpl$$InjectAdapter extends Binding<EntityTransactionImpl>
    implements MembersInjector<EntityTransactionImpl> {
  private Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory> persistenceFactory;

  public EntityTransactionImpl$$InjectAdapter() {
    super(null, "members/au.com.cybersearch2.classyjpa.transaction.EntityTransactionImpl", NOT_SINGLETON, EntityTransactionImpl.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    persistenceFactory = (Binding<au.com.cybersearch2.classyjpa.persist.PersistenceFactory>) linker.requestBinding("au.com.cybersearch2.classyjpa.persist.PersistenceFactory", EntityTransactionImpl.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(persistenceFactory);
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<EntityTransactionImpl>}.
   */
  @Override
  public void injectMembers(EntityTransactionImpl object) {
    object.persistenceFactory = persistenceFactory.get();
  }

}
